### ISSUE TITLE
Can't install suit rock

### ISSUE THREAD

**Issue by milen-prg** [ScriptTiger/LuaJIT-For-Windows#2]
C:\LuaJIT-For-Windows>luarocks install  --global suit
Installing https://luarocks.org/suit-0.1-1.rockspec

Error: C:\Users\mlap\AppData\Local\Temp/luarocks_luarocks-rockspec-suit-0.1-1-9702/suit-0.1-1.rockspec: Unknown field 1 (using rockspec format 1.0)

**Comment by ScriptTiger** [comment]
That particular rockspec is actually not formatted correctly and won't work with any modern version of LuaRocks. Modern LuaRocks rockspecs require the "homepage" and "license" fields within the "description". 

That being said, for your convenience, I have repackaged that particular rock for you. However, please be cautioned to use at your own risk, as that package is clearly outdated. To install it, simply extract the rock from the ZIP file attached to this comment and install it. You use the `luarocks install` command just as you would normally, except you point to the local path of the rock file (i.e. `luarocks install suit-0.1-1.src.rock`).
[suit-0.1-1.src.rock.zip](https://github.com/ScriptTiger/LuaJIT-For-Windows/files/11124176/suit-0.1-1.src.rock.zip)

Let me know if this helped you!

**Comment by ScriptTiger** [comment]
In the latest release, I have also added git. This means, instead of using the rock I attached in my last comment, you could alternative also install the rockspec attached to this comment, which I have updated to work with the current LuaRocks specifications. In the rock attached in my last comment, it contains the full `suit` package. In the rockspec attached to this comment, it only contains the information needed to download the `suit` package via git, and then proceeds to install the downloaded package. As noted in my last comment, however, this package is clearly outdated and does not meet current LuaRocks specifications, so use at your own risk.
[suit-0.1-1.rockspec.zip](https://github.com/ScriptTiger/LuaJIT-For-Windows/files/11128509/suit-0.1-1.rockspec.zip)

I will close this issue, as I feel I have addressed all possible avenues as they relate to the LuaJIT For Windows package. For further help on the `suit` package, I would recommend contacting the maintainer and requesting they update their rockspec, along with anything else that may need to be updated.

While I am closing this issue as solved, please feel free to reply any further follow-up comments you may have. And thanks for your interest in the project!

**Comment by milen-prg** [comment]
Thank you, the modified package is successfully installed!

**Comment by milen-prg** [comment]
Please, I want to ask one more thing:

Is it possible to install rock with C library dependence, as in your distribution is included C compilatior. For example at try to install luarocks fltk4lua:

C:\LuaJIT-For-Windows>luarocks install  --global fltk4lua
Installing https://luarocks.org/fltk4lua-0.2-1.src.rock

Error: Could not find header file for FLTK
  No file FL/Fl.h in c:/external/include
  No file FL/Fl.h in c:/mingw/include
  No file FL/Fl.h in c:/windows/system32/include
You may have to install FLTK in your system and/or pass FLTK_DIR or FLTK_INCDIR to the luarocks command.
Example: luarocks install fltk4lua FLTK_DIR=/usr/local

Or for sdl2:

C:\LuaJIT-For-Windows>luarocks install  --global lua-sdl2
Installing https://luarocks.org/lua-sdl2-2.0.5.6.0-1.src.rock

Error: Could not find header file for SDL2
  No file SDL_scancode.h in c:/external/include
  No file SDL_scancode.h in c:/mingw/include
  No file SDL_scancode.h in c:/windows/system32/include
You may have to install SDL2 in your system and/or pass SDL2_DIR or SDL2_INCDIR to the luarocks command.
Example: luarocks install lua-sdl2 SDL2_DIR=/usr/local

I apologize, but I have Python background, not experienced in C-bindings and just start to learn Lua, and want to have some graphics library.

**Comment by ScriptTiger** [comment]
> Is it possible to install rock with C library dependence, as in your distribution is included C compilatior.

Yes, it is. 

> I apologize, but I have Python background, not experienced in C-bindings and just start to learn Lua, and want to have some graphics library.

No worries, we all start somewhere. In order to bind to the C libraries, you must have them available on your local machine. However, LuaRocks does not download and build external dependencies.

For example:
> Error: Could not find header file for FLTK
> No file FL/Fl.h in c:/external/include
> No file FL/Fl.h in c:/mingw/include
> No file FL/Fl.h in c:/windows/system32/include
> You may have to install FLTK in your system and/or pass FLTK_DIR or FLTK_INCDIR to the luarocks command.
> Example: luarocks install fltk4lua FLTK_DIR=/usr/local

The file it's looking for is located in the fltk package:
https://github.com/fltk/fltk/blob/master/FL/Fl.H

`fltk4lua-0.2-1.rockspec`:
> external_dependencies = {
>   platforms = {
>     windows = {
>       FLTK = {
>         header = "FL/Fl",
>         library = "fltk"
>       }
>     },
>     unix = {
>       FLTK = {
>         program = "fltk-config"
>       }
>     }
>   }
> }

As stated in the `fltk4lua-0.2-1.rockspec`, you need both the `FL/Fl` header file and the `fltk` lib file. In order to get the lib file, you're going to have to build it. These are all things you will have to do on your own before trying to link to them. You might also try looking for pre-built packages online.
